//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICAMENTOXPEDIDO
    {
        public int Pedido { get; set; }
        public string Medicamento { get; set; }
        public bool Activo { get; set; }
    
        public virtual MEDICAMENTO MEDICAMENTO1 { get; set; }
        public virtual PEDIDO PEDIDO1 { get; set; }
    }
}
