//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GasStationPharmacyEntities : DbContext
    {
        public GasStationPharmacyEntities()
            : base("name=GasStationPharmacyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRADORXSUCURSAL> ADMINISTRADORXSUCURSALs { get; set; }
        public virtual DbSet<CASAFARMACEUTICA> CASAFARMACEUTICAs { get; set; }
        public virtual DbSet<CLIENTE> CLIENTEs { get; set; }
        public virtual DbSet<COMPAÑIA> COMPAÑIA { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOes { get; set; }
        public virtual DbSet<MEDICAMENTO> MEDICAMENTOes { get; set; }
        public virtual DbSet<MEDICAMENTOXPEDIDO> MEDICAMENTOXPEDIDOes { get; set; }
        public virtual DbSet<MEDICAMENTOXRECETA> MEDICAMENTOXRECETAs { get; set; }
        public virtual DbSet<PADECIMIENTO> PADECIMIENTOes { get; set; }
        public virtual DbSet<PEDIDO> PEDIDOes { get; set; }
        public virtual DbSet<RECETA> RECETAs { get; set; }
        public virtual DbSet<ROL> ROLs { get; set; }
        public virtual DbSet<ROLXDEPENDIENTE> ROLXDEPENDIENTEs { get; set; }
        public virtual DbSet<SUCURSAL> SUCURSALs { get; set; }
        public virtual DbSet<TELEFONOXCLIENTE> TELEFONOXCLIENTEs { get; set; }
    }
}
