//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO()
        {
            this.MEDICAMENTOXPEDIDOes = new HashSet<MEDICAMENTOXPEDIDO>();
        }
    
        public int Numero { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaRecojo { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Sucursal { get; set; }
        public int Cliente { get; set; }
        public bool Activo { get; set; }
    
        public virtual CLIENTE CLIENTE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICAMENTOXPEDIDO> MEDICAMENTOXPEDIDOes { get; set; }
        public virtual SUCURSAL SUCURSAL1 { get; set; }
    }
}
